# Generated by Django 4.2.2 on 2023-06-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
